import type { NextPage } from "next";
import Head from "next/head";
import Feed from "../components/Feed";
import Navbar from "../components/Navbar";
import { db } from "../firebase";
import {
  collection,
  getDocs,
  query,
  orderBy,
  Timestamp,
} from "firebase/firestore";
import { useEffect, useState } from "react";

export interface IPost {
  id?: string;
  caption: string;
  comments: {
    comment: string;
    createdAt: Timestamp;
    name: string;
    userPhoto: string;
  }[];
  likes: string[];
  createdAt: Timestamp;
  email: string;
  image: string;
  name: string;
  userPhoto: string;
}

export async function getServerSideProps() {
  const postsSnapshot = await getDocs(
    query(collection(db, "posts"), orderBy("createdAt", "desc"))
  );
  const postsArray = postsSnapshot.docs.map((doc) => {
    return { ...JSON.parse(JSON.stringify(doc.data())), id: doc.id };
  });

  return {
    props: { postsData: postsArray },
  };
}

const Home: NextPage = ({ postsData }: any) => {
  const [posts, setPosts] = useState<IPost[]>([]);

  useEffect(() => {
    setPosts(postsData);
  }, [postsData]);

  return (
    <div>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Feed posts={posts} />
    </div>
  );
};

export default Home;
